### ISSUE TITLE
Falta la validacion de datos de los parametros mandados por req.body de las rutas de Tasks

### ISSUE THREAD

**Issue by JRS-Developer** [JRS-Developer/pf-server#2]
### Propuesta para la validacion
Para la validación creo que podriamos implementar una librería que nos permita validar los parámetros de una forma muy fácil, entre las opciones que hay son [Joi](https://joi.dev/api/) y [Yup](https://github.com/jquense/yup), sino pues se pueden realizar validaciones con los típicos if y else pero es mucho mas verboso de hacer.

**Comment by ferwinred** [comment]
si nos facilita la validación que hay que hacer con firebase sería genial

**Comment by JRS-Developer** [comment]
> si nos facilita la validación que hay que hacer con firebase sería genial

No, no es relacionado a firebase, si Nico no termina con ese tema mañana, me pondré yo a investigar firebase.
